### ISSUE TITLE
Differences with of the official kinvey-angular library?

### ISSUE THREAD

**Issue by levithomason** [ninjatronic/angular-kinvey#25]
Hi there, just wondering what the differences are between this library and the officially maintained kinvey-angular library / $kinvey service?

http://devcenter.kinvey.com/angular/guides/getting-started

I see angular-kinvey uses the $resrouce paradigm (opposed to Kinvey's $kinvey service).  Though the $kinvey service behind the scenes relies on $http which is also what $resource also relies on.

Any info is much appreciated, thanks!

**Comment by ninjatronic** [comment]
Hi @levithomason 

As it turns out, I'm now one of the maintainers for the official Kinvey AngularJS library. I highly recommend you use that one.

However should you still be interested in using a different one there are a few differences between the two implementations. I've made a couple of lists below, to help you choose, and I'm paging @edatkinvey to comment as well.

### Benefits of `angular-kinvey`
- [Tight `$resource` integration](https://github.com/ninjatronic/angular-kinvey/wiki/Getting-Started#response-structure)
- Tight [integration of init process into `config` and `run` phases](https://github.com/ninjatronic/angular-kinvey/wiki/Getting-Started#configuration) of an Angular app
- [Simple, POJO based query definitions](https://github.com/ninjatronic/angular-kinvey/wiki/Data-Store#compound-queries)
- [Automatic reference detection](https://github.com/ninjatronic/angular-kinvey/wiki/Data-Store#automatic-referencing)

### Benefits of official Kinvey implementation
- **[Caching and Offline support](http://devcenter.kinvey.com/angular/guides/caching-offline)**
- [File streaming](http://devcenter.kinvey.com/angular/guides/files#Streaming)
- Easy-to-use [permissions and security](http://devcenter.kinvey.com/angular/guides/security)
- All the other Kinvey resources that apply, like support and the [Devcenter](http://devcenter.kinvey.com/angular/guides)

A few things to consider there for you. Best of luck with your decision.

**Comment by ninjatronic** [comment]
Hi @levithomason 

As it turns out, I'm now one of the maintainers for the official Kinvey AngularJS library. I highly recommend you use that one.

Thanks

**Comment by levithomason** [comment]
@ninjatronic Awesome, that's great news.  I'm the lead web developer at @GravityJack.  I'd like to update you on our open source work thus far with Kinvey and ask a couple questions.  I'll ping @edatkinvey as I'd like to hear his feedback as well.

**Gravity Jack Kinvey Projects**
- [kinvey-angular](https://github.com/GravityJack/bower-kinvey-angular), we're hosting the official library on Bower `bower install kinvey-angular`.
- [Kinvey Groups](https://github.com/GravityJack/kinvey-groups), a web console for managing User Groups.
- [Kinvey Angular Mock](https://github.com/GravityJack/kinvey-angular-mock), mock `$kinvey` service for unit testing.

**Angular Library Questions**
1. User Group support?
   Currently, you need to write your own calls to the User Group endpoints.  It would be very helpful to have access to the User Groups via the `$kinvey` service rather than the REST API only.  Perhaps this is already a thought at Kinvey as [line 153](https://github.com/GravityJack/bower-kinvey-angular/blob/master/kinvey-angular.js#L153) in kinvey-angular.js contains `/*var USER_GROUPS = 'group';*/` listed under `// Top-level functionality.`.
2. Custom endpoint execution options for `$kinvey.execute()`?
   It's great that we can call custom endpoints with a custom body.  It'd be super useful to be able to call endpoint with a custom method, headers, and body.  This way we can write RESTful endpoints, instead of '/create-object'  '/get-objects', etc.
3. Why not open source it?
   We could move this conversation to the official repo and get some PRs going :)

Thanks for your contribution to the community thus far, hope we can work together soon.

**Comment by ninjatronic** [comment]
Hi @levithomason 

Wow - that's quite the list of Kinvey-based open-source projects! It's awesome to see the tools that people build on Kinvey - partly because it means that devs love our product, and we're doing our jobs right when that's the case, but mostly because it shows us what we've missed.

None of the issues you've tried to address with these projects are new to us, but our radar gets so full sometimes that these things can drop off, especially when there is a perceived lack of community interest.

I don't think that any of the issues you've tried to address with these projects are new to us, but unfortunately the comments section on an issue on my old, pre-official implementation isn't the place to reach out for so much support from Kinvey! (I wish it was, but this repo just isn't that popular). I'd like to take this opportunity to point you at [our support forums](https://support.kinvey.com/), which is where you'll get the right sets of eyes on these questions, and more information on what we're doing about these things than I could give you off the tip of my brain here!

Thanks for your feedback, and for reaching out with this.
