### ISSUE TITLE
Using `Content-Length` not allowed

### ISSUE THREAD

**Issue by kenhkan** [ninjatronic/angular-kinvey#8]
It's me again. :)

Apparently some modern browsers don't like it when you set the `Content-Length` header manually. For instance, Chrome stops execution upon encountering that header in an XHR. It turns out to be in the spec too (under 4.6.2): http://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader-method

The offending line: https://github.com/ninjatronic/angular-kinvey/blob/master/kinvey.js#L83

I was thinking of submitting a PR, but I'm not sure how you'd approach this as older browsers may not populate this field.

**Comment by ninjatronic** [comment]
Hi @kenhkan 

Yes I had spotted this before, but hadn't decided on what to do about it. Modern browsers will automatically decorate any outgoing request with this header, but I'm not sure about which earlier browsers (if any) will not support this.

Angular officially supports IE8 and upwards, and as far as I can tell IE8 will fill this header. Both Firefox and Chrome are happily filling it too.

Since it seems to be supported by most modern browsers I'll include this. If there are problems with older browsers in the future I'll revisit it.

Cheers

**Comment by kenhkan** [comment]
Great! Love the speed. Thank you.

**Comment by ninjatronic** [comment]
No problem. I've scheduled a release for next Friday, so hopefully that's going to be soon enough for you to use the bower version in your project?

If you encounter any other problems, please let me know.

(I'm always interested to see things people make with my code also :))

**Comment by kenhkan** [comment]
No worries on release, unless it's your scheduled release. I always just `bower link` and build my project that way for pending changes. Works like a charm for client-side projects.

This thing is pretty well thought out. Miles better than Kinvey's own because of its Angular-focus. I'll definitely keep you posted.

**Comment by ninjatronic** [comment]
I'm trying to schedule releases and structure the delivery plan of this project a bit more formally, because up until now it's been quite haphazard. Bugfix releases are planned (if needed) and there is a v2.x release planned as well which will add some more functionality. Hopefully the presence of Milestones will also encourage people who are using it to request features they want in a timely manner :).

There was some discussion with the guys at Kinvey in the inception phase of this project about how to approach it, and one of the engineers there [started hacking on an app](https://github.com/Myztiq/bgtrackr-angular) with it a few weeks ago but I think that's fallen by the wayside now.

I think their HTML5 library is more fully featured as it has things like offline caching now, but I've always found using these things in angular can be a real pain because of the amount of leveraging code that has to wrap the API calls, and it's generally a lot nicer to have an Angular specific library.
